### ISSUE TITLE
Add .gitattributes file

### ISSUE THREAD

**Issue by paulonotz0r** [ifactory-solutions/inside-client#10]
Atteding to @Jefferson227 [comment](https://github.com/ifactory-solutions/inside-client/pull/8#pullrequestreview-64294435) on #8, the end-of-line normalization should be handled with `.gitattributes` file. Setting `* text=auto`  as default behavior to automatically normalize line endings, which is mentioned on [git docs](https://git-scm.com/docs/gitattributes#gitattributes-Settostringvalueauto).

**Comment by wellyal** [comment]
Wouldn't be better to resolve this issue on #8. Since is not closed or merged yet. What you think?

**Comment by paulonotz0r** [comment]
I think this issue is not directly related to the #8, because they come from different contexts. Once #8 it's about commit structure and normalize line endings it's about code (and/or file) structure. In addition, we can think about a need, for example, reset this configuration or #8 configuration.

**Comment by jvcjunior** [comment]
Hey @wellyal I agree with @paulonotz0r. Imagine we want to reset or remove one feature and don't want to touch on the another one. In this case, we would have to separate the code related with each funcionality and then create a new commit(just like before), you know? It's features with different purpose.

**Comment by jvcjunior** [comment]
@paulonotz0r would you like to get this one?

**Comment by paulonotz0r** [comment]
@jvcjunior Sure! I'll create a branch and make a PR for this soon.

**Comment by jvcjunior** [comment]
Awesome!
