### ISSUE TITLE
Proposal of a README.md Template Model

### ISSUE THREAD

**Issue by wellyal** [ifactory-solutions/inside-client#11]
I've been searching for good and clean readme.md templates for open source projects. Bellow is the one I found more interesting. What you guys think?

https://gist.github.com/PurpleBooth/109311bb0361f32d87a2

**Comment by italopessoa** [comment]
Looks good and clean. 😃 
Maybe we can use this issue to choose other templates. 
Like CONTRIBUITING.md

**Comment by jvcjunior** [comment]
Looks good to start! 😃

**Comment by D40661195** [comment]
Looks good to me, however, I would suggest to add a section called "Contributors" using this approach https://github.com/kentcdodds/all-contributors

What do you think about guys?

**Comment by wellyal** [comment]
@italopessoa np for me. @jouderianjr  aka @D40661195 awesome! I'll PR this tomorrow morning. 

**[OFFTOPIC]** @D40661195 => Btw, You should change this username :-D

**Comment by jouderianjr** [comment]
Ops, was from a wrong account :x

Original comment:

```
Looks good to me, however, I would suggest to add a section 
called "Contributors" using this approach https://github.com/kentcdodds/all-contributors

What do you think about guys?
```

**Comment by italopessoa** [comment]
I agree with @jouderianjr / @d40661195. We shouldn't expect someone to click on the contributor's link, as on the template that @wellyal suggested. And I go further, it must be on the README top :octocat:  
# The world will see our powweeeeeeeeeeer
