### ISSUE TITLE
Commit message conventions

### ISSUE THREAD

**Issue by jvcjunior** [ifactory-solutions/inside-client#2]
Let's try? What are some thoughts on this subject?

Useful links to explore:
[https://conventionalcommits.org/](https://conventionalcommits.org/)
[https://github.com/kazupon/git-commit-message-convention](https://github.com/kazupon/git-commit-message-convention)
[https://github.com/marionebl/commitlint](https://github.com/marionebl/commitlint)

**Comment by wellyal** [comment]
From the first link provided we could make use of the **feat** and **fix** label types. **Breaking Changes** doesn't make sense since were not building an API.

`feat(parser): add ability to parse` -> Looks clean and beautiful to me

**Comment by wellyal** [comment]
Heres what I think would be great **labels type** to begin.

**feat** => New feature
**fix** => Fix some bug
**imp** => Improvements do the project (performance, code etc)
**doc** => Adding or revising doc

**Comment by jvcjunior** [comment]
Awesome @wellyal. I think it's a good start. 

What do you think @jouderianjr @Jefferson227 @laurindo @italopessoa ?

**Comment by italopessoa** [comment]
I don't know if any of you read my comment before this last edit. Please ignore.

Looks good! 😸

**Comment by yannbf** [comment]
To add to what @wellyal said, I really like the [semantic commit messages](https://seesparkbox.com/foundry/semantic_commit_messages).

We could also use this guy to help maintain the commit quality: https://github.com/typicode/husky

**Comment by andrelas1** [comment]
That's a great idea. I also enjoyed the semantic commit messages and husky.  Thumbs up to this :+1: 
In addition, this project https://github.com/gitpoint/git-point has some cool stuff about pre commit processes.

**Comment by jvcjunior** [comment]
Hey @yannbf I'm doing that on issue #4 using husky. It's almost done. ;)

**Comment by jvcjunior** [comment]
Hey @jouderianjr @wellyal @yannbf @andrelas1 @italopessoa, don't you think we can close this issue since we already created the commit lint and I also created the first version of our commit msg documentation. It's on the wiki pages. Let me know your thoughts, please!

**Comment by wellyal** [comment]
@jvcjunior I think it should be closed with a CONTRIBUTING.md file PR.

**Comment by jvcjunior** [comment]
ok @wellyal!
