### ISSUE TITLE
Add React Router

### ISSUE THREAD

**Issue by jvcjunior** [ifactory-solutions/inside-client#32]

**Comment by BrianCortes** [comment]
@jvcjunior what version react-router do you want ? 🤔

**Comment by italopessoa** [comment]
@BrianCortes we intend to use the latest version (compatible with react latest version).

**Comment by BrianCortes** [comment]
@italopessoa I will try to add react router 4 🥇

**Comment by italopessoa** [comment]
Cool! Feel free to contact us on gitter :)

**Comment by BrianCortes** [comment]
@italopessoa, @jvcjunior  I have a problem when I am trying to do a commit 
<img width="598" alt="captura de pantalla 2017-10-28 a la s 9 30 21 am" src="https://user-images.githubusercontent.com/18728297/32135288-0af6e034-bbc2-11e7-8c41-db75341c3cf3.png">

**Comment by jourdanrodrigues** [comment]
@BrianCortes 

- Use double quotes;
- Put a space between the parameter (-m) and the message;
- You must use a "change type", like "feature: message" or "config: message".

Fix these and you'll be fine.

Happy for your contribution, btw.
