### ISSUE TITLE
Create Issue template

### ISSUE THREAD

**Issue by jvcjunior** [ifactory-solutions/inside-client#41]

**Comment by feedbacker1991** [comment]
I want to take this one.

**Comment by jvcjunior** [comment]
Hey @feedbacker1991. Go ahead but take a look on this PR please:
https://github.com/ifactory-solutions/awesome-react-app/pull/46

Try to follow similar idea

**Comment by feedbacker1991** [comment]
I am on it.

**Comment by jvcjunior** [comment]
Nice @feedbacker1991

**Comment by paulonotz0r** [comment]
I think we can improve this. @feedbacker1991 added a nice template in #42. But I though better and I don't agree with the [first sentence](https://github.com/ifactory-solutions/inside-client/pull/42/files#diff-0b6c1416b1293274c4e2d11fb49e1795R1). 

In my opinion, issue tracker isn't just for reporting bugs, but also to discuss (or make a question) about an improvement or a new feature, for example. And we could use StackOverflow to reference bugs, questions, discussions, etc.

I've taken a look into [create-react-app issue template](https://github.com/facebookincubator/create-react-app/issues/new) and we could follow the first section style, which gives the option of create a free form discussion/question if the issue isn't related to a bug report.

**Comment by wellyal** [comment]
I think its too much for opening an issue.
