### ISSUE TITLE
Create CONTRIBUTING.md file

### ISSUE THREAD

**Issue by jvcjunior** [ifactory-solutions/inside-client#6]
- Search about how open source projects allow contribution
- Propose guidelines for contributions to the project

**Comment by wellyal** [comment]
https://gist.github.com/PurpleBooth/b24679402957c63ec426

**Comment by italopessoa** [comment]
Add [DOs and DON'Ts](https://github.com/dotnet/coreclr/blob/master/Documentation/project-docs/contributing.md#dos-and-donts)

Some principles to adopt:
**KISS**: Keep it simple, Stupid.
**YAGNI**: You Ain't Gonna Need It.

**Comment by jvcjunior** [comment]
We can discuss about the contributing file here @adrianobrito ;)
