### ISSUE TITLE
Add Content to Wiki - Explain how commit messages works 

### ISSUE THREAD

**Issue by jvcjunior** [ifactory-solutions/inside-client#9]
Since we are going to use commitlint and husky to avoid 💩 commit messages it would be good to explain how our commit messages should be formatted. 

Please add on our wiki how that works based on the rules added to the commitlint file(commitlint/index.js).

**Comment by yannbf** [comment]
Here's a great reference: http://karma-runner.github.io/1.0/dev/git-commit-msg.html

**Comment by laurindo** [comment]
This issues was finished? My develop branch has a folder "commitlint" with "index.js"
![commitlint](https://user-images.githubusercontent.com/2501144/30711392-f500c1c8-9ede-11e7-97a6-2f38038cb868.png)

**Comment by jvcjunior** [comment]
Hey @laurindo this folder and index file is related with the commit lint and not with the documentation. This issue is about creating a wiki page with details about the commit messages. To be honest, I just got this issue, take a look at [https://github.com/ifactory-solutions/inside-client/wiki](https://github.com/ifactory-solutions/inside-client/wiki)

**Comment by laurindo** [comment]
Ok @jvcjunior . I understood now. :smile:
